# Format: org/repo|source_dir|ram_mib|cpus
keycloak/keycloak|/home/mvavrik/sources/keycloak|12288|6
quarkusio/quarkus|/home/mvavrik/sources/quarkus|16384|8
apache/camel-k|/home/mvavrik/sources/camel-k|8192|4
# Default (when no match):
DEFAULT||8192|4
